[package]
name = "compositor"
version = "0.0.1"
authors = ["Akane"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smithay = "0.3.0"
